---
- name: Add Route53 CNAME entry
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create or update CNAME entry
      community.aws.route53:
        state: present
        zone: "{{ zone_name }}"
        record: "{{ global_name }}"
        type: CNAME
        ttl: 300
        value: "{{ target_names }}"
        wait: yes
        overwrite: yes

