---
- name: Add Route53 CNAME entry
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create or update CNAME entry
      community.aws.route53:
        state: present
        zone: mouimetlab.com
        record: global-app1.mouimetlab.com
        type: CNAME
        ttl: 300
        value: "{{ target_names }}"
        wait: yes
        overwrite: yes
        
